apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: seed-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
      exemplarTraceIdDestinations: []

  - name: Alertmanager
    type: alertmanager
    uid: seed-alertmanager
    access: proxy
    url: http://alertmanager:9093
    isDefault: false
    editable: false
    jsonData:
      implementation: prometheus
